### PR TITLE
RedfishPkg/ConfigHandler: Remove [Depex] section from INF file

### LINKED ISSUE #12394: [Bug]: Remove [DEPEX] section from RedfishConfigHandler driver
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### What packages are impacted?

RedfishPkg

### Which targets are impacted by this bug?

DEBUG, NO-TARGET, NOOPT, RELEASE

### Current Behavior

Remove [DEPEX] section from RedfishConfigHandler driver, as it is a UEFI driver.

### Expected Behavior

No dependency section in the INF file.

### Steps To Reproduce

N/A

### Build Environment

```markdown
- OS(s): All
- Tool Chain(s): All
```

### Version Information

```text
b7cf7e465c402f9b32dcadc791ba37f2db750522
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by changab**
UEFI driver shouldn't have the [Depex] section in INF file. Remove Redfish Credential Protocol in the dependency section and locate it when the UEFI driver is connected to execute.

# Description
fixes: #12394

UEFI driver shouldn't have a [Depex] section.

- [ ] Breaking change?
  - **Breaking change** - Does this PR cause a break in build or boot behavior?
  - Examples: Does it add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does this PR have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does this PR include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested
Verified the functionality on AMD platform.

## Integration Instructions
N/A

### CODE REVIEW

**Comment by khaliid2040** [comment]
Please link the issue with the PR probably. Suggestion: 

Use `fixes: #12394` instead of  "Fix the issue #12394."

This auto-closes the issue when PR is merged.

File: RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c [hunk 1]
```diff
@@ -171,6 +172,20 @@ RedfishConfigDriverBindingSupported (
     &gEfiRestExServiceBindingProtocolGuid,
     ChildHandle
     );
+
+  //
+  // Check if the Redfish credential protocol is installed or not.
+  //
+  Status = RedfishConfigCommonInit ();
```
Comment (nicklela) [inline RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c]: Hmm... I am not a fan of calling init function in supported function. The end-of-dxe event and exit-boot-service event are created multiple times.

Could we just test and see if gEdkIIRedfishCredentialProtocolGuid is installed or not?

Comment (changab) [reply RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c]: Yes, we can test this procotol in the Support function and locate it in the Start().
Also, thanks for catching the multiple event registration issue.

File: RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerCommon.h [hunk 2]
```diff
@@ -3,12 +3,14 @@
...
 
   (C) Copyright 2021 Hewlett Packard Enterprise Development LP<BR>
+  Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.<BR>
 
   SPDX-License-Identifier: BSD-2-Clause-Patent
 
 **/
 
-#pragma once
+#ifndef EFI_REDFISH_CONFIG_HANDLER_COMMON_H_
```
Comment (nicklela) [inline RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerCommon.h]: is this intentional?

**Review by nicklela — COMMENTED** [review]
Looks good to me but I have one minor comment.

File: RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerCommon.h (hunk 2 above)
Comment (EricGao2015) [reply RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerCommon.h]: Edk2 has replaced include guards with pragma once, please refer https://github.com/tianocore/edk2/pull/12149.

**Comment by EricGao2015** [comment]
Look good for me. But it may be better that moves the locate protocol operation from Supported() to start(), because Supported() is called frequently.

**Comment by changab** [comment]
@EricGao2015, @nicklela  and @igorkulchytskyy. Please check this out again.

**Comment by igorkulchytskyy** [comment]
> Look good for me. But it may be better that moves the locate protocol operation from Supported() to start(), because Supported() is called frequently.

Since right after the success of Supported() function, Start() function is called, and we call LocateProtocol at the end of Supported() function, it would be the same number of calls.
But it is better to check all required conditions in Supported() function.

**Review by igorkulchytskyy — APPROVED** [review]

**Review by EricGao2015 — APPROVED** [review]

**Comment by changab** [comment]
> > Look good for me. But it may be better that moves the locate protocol operation from Supported() to start(), because Supported() is called frequently.
> 
> Since right after the success of Supported() function, Start() function is called, and we call LocateProtocol at the end of Supported() function, it would be the same number of calls. But it is better to check all required conditions in Supported() function.

HI @igorkulchytskyy, we check gEdkIIRedfishCredentialProtocolGuid installation in Support() to ensure we are good to start the driver. I think this logic is fine by itself, or would you like to have a variable to record the protocol interface and skip LocateProtocol() when the protocol interface is not NULL?

**Comment by igorkulchytskyy** [comment]
> HI @igorkulchytskyy, we check gEdkIIRedfishCredentialProtocolGuid installation in Support() to ensure we are good to start the driver. I think this logic is fine by itself, or would you like to have a variable to record the protocol interface and skip LocateProtocol() when the protocol interface is not NULL?
I think the current logic is good

**Review by nicklela — APPROVED** [review]

**Comment by changab** [comment]
> > HI @igorkulchytskyy, we check gEdkIIRedfishCredentialProtocolGuid installation in Support() to ensure we are good to start the driver. I think this logic is fine by itself, or would you like to have a variable to record the protocol interface and skip LocateProtocol() when the protocol interface is not NULL?
> > I think the current logic is good

Thanks!
