### PR TITLE
MdeModulePkg: DxeCore: Set Image Memory Protections Through GCD

### LINKED ISSUE #10771: [Bug]: DXE core memory protection feature might cause inconsistency between GCD internal data structure with CPU page table
### Is there an existing issue for this?

- [x] I have searched existing issues

### Bug Type

- [x] Firmware
- [ ] Tool
- [ ] Unit Test

### Code first?

- [ ] Yes

### What packages are impacted?

MdeModulePkg

### Which targets are impacted by this bug?

DEBUG, RELEASE

### Current Behavior

When we enable DXE core memory protection feature, if we set some GCD irrelevent attributes like EFI_MEMORY_SP or EFI_MEMORY_CPU_CRYPTO via GCD SetMemorySpaceAttributes (), it will cause page fault except.

### Expected Behavior

We can still invoke SetMemorySpaceAttributes () successfully to **append** EFI_MEMORY_SP or EFI_MEMORY_CPU_CRYPTO 

### Steps To Reproduce

1. Set the following two platform PCD to enable memory protection.
PcdSetNxForStack| TRUE
PcdDxeNxMemoryProtectionPolicy| 0x7FD5

2. Invoke GCD SetMemorySpaceAttributes () API in later DXE phase to append EFI_MEMORY_SP or EFI_MEMORY_CPU_CRYPTO (keep the original attributes) 
3. System will have page fault exception

### Build Environment

```markdown
- OS(s):Windows 11
- Tool Chain(s): VS2019
```

### Version Information

```text
Commit: f979f51157c5560c658537ea2a488b7a8439e463
```

### Urgency

High

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

The root cause of this issue is that Edk2\MdeModulePkg\Core\Dxe\Misc\MemoryProtection.c (line 1294) directly uses CPU arch protocol to clear XP in page table when loading DXE driver for execution, but it fails to update the GCD internal data structure according (the memory range still makes as XP attribute):
gCpu->SetMemoryAttributes (gCpu, Memory, Length, NewAttributes);

Later invoking of GCD SetMemorySpaceAttributes () will incorrectly re-apply the incorrect XP attribute and make it take effect in the final page table. When CPU executes the memory, it triggers the page fault exception.

### PR DESCRIPTION
**Pull request by os-d**
# Description

Today, SetUefiImageMemoryAttributes calls directly to the CPU Arch protocol to set EFI_MEMORY_XP or EFI_MEMORY_RO on image memory. However, this bypasses the GCD and so the GCD is out of sync with the actual state of memory.

This can cause an issue in the scenario where a new attribute is being set (whether a virtual attribute or a real HW attribute), if the GCD attributes are queried for a region and the new attribute is appended to the existing GCD attributes (which are incorrect), then the incorrect attributes can get applied. This can result in setting EFI_MEMORY_XP on code sections of images and causing an execution fault.

This patch updates SetUefiImageMemoryAttributes to call into the GCD to update the attributes there and let the GCD code call into the CPU Arch protocol to update the page table.

While here, do a couple small updates in the function to improve error handling and logging.

Closes #10771 .

- [ ] Breaking change?
  - **Breaking change** - Does this PR cause a break in build or boot behavior?
  - Examples: Does it add a new library class or move a module to a different repo.
- [ ] Impacts security?
  - **Security** - Does this PR have a direct security impact?
  - Examples: Crypto algorithm change or buffer overflow fix.
- [ ] Includes tests?
  - **Tests** - Does this PR include any explicit test code?
  - Examples: Unit tests or integration tests.

## How This Was Tested

Booted OVMF and ArmVirt to Windows and Linux with the change; used the repro scenario to confirm a boot to Windows occurs.

## Integration Instructions

N/A.

### CODE REVIEW

**Comment by os-d** [comment]
@qhuang8 , can you confirm that this patch resolves the crash you see?

File: MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c [hunk 1]
```diff
@@ -196,14 +196,41 @@ SetUefiImageMemoryAttributes (
   UINT64                           FinalAttributes;
 
   Status = CoreGetMemorySpaceDescriptor (BaseAddress, &Descriptor);
-  ASSERT_EFI_ERROR (Status);
+  if (EFI_ERROR (Status)) {
+    DEBUG ((
+      DEBUG_ERROR,
+      "%a - Failed to get memory space descriptor for address %llx with status %r. Cannot protect image.\n",
```
Comment (makubacki) [inline MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c:202]: Missing `__func__`?

Comment (os-d) [reply MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c:202]: Thanks, fixed.

File: MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c [hunk 2]
```diff
@@ -196,14 +196,41 @@ SetUefiImageMemoryAttributes (
...
+  if (EFI_ERROR (Status)) {
+    DEBUG ((
+      DEBUG_ERROR,
+      "%a failed on %llx of length %llx with attributes %llx - %r\n",
+      Status,
+      __func__,
+      BaseAddress,
+      Length,
+      FinalAttributes
+      ));
```
[the remark this answers is not in the document]
Comment (os-d) [reply MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c]: Thanks, fixed.

**Review by lgao4 — APPROVED** [review]

**Comment by lgao4** [comment]
@os-d , the code change looks good. But, I don't understand what's wrong in CI.

**Comment by os-d** [comment]
> @os-d , the code change looks good. But, I don't understand what's wrong in CI.

@lgao4 thanks for the review! This was my bad, I didn't set the capabilities first if required. I have updated the PR to do this and tested one of the failing cases locally and it now passes. Confirming with the original reproer that this fixes their issue.

**Comment by os-d** [comment]
@lgao4 can you please re-review the PR? I have made significant changes since your initial review to handle the non-aligned image case. The original reproer has confirmed it fixes the OVMF repro, though was having issues integrating into 2402 to test on a physical platform. I am testing on a physical system now.

**Comment by lgao4** [comment]
> @lgao4 can you please re-review the PR? I have made significant changes since your initial review to handle the non-aligned image case. The original reproer has confirmed it fixes the OVMF repro, though was having issues integrating into 2402 to test on a physical platform. I am testing on a physical system now.

Thanksf for your update. New version patch is good to me.
